# name: widgetbook
name: widgetbook_workspace # this is renamed to widgetbook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
# ここに、作成したFlutterプロジェクトのパスを記述
# 上の階層にあるwidget_book_tutorialを参照する
  widget_book_tutorial:
    path: ../

  flutter:
    sdk: flutter
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
